version: 0.0

os: linux
files:
  - source: index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  AfterInstall:
    - location: scripts/after-install.sh
  ValidateService:
    - location: scripts/test.sh
      timeout: 60
